spring.application.name=analyticsservice

server.port=9010

spring.cloud.config.enabled=true

spring.config.import=optional:configserver:http://localhost:8888

# Eureka Client Configuration
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Eureka Instance Configuration
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.instance.hostname=localhost