spring.application.name=notificationservice

server.port=7010

spring.cloud.config.enabled=true

spring.config.import=optional:configserver:http://localhost:8888

# Spring Batch Configuration
# Désactive le démarrage automatique des jobs au démarrage de l'application
spring.batch.job.enabled=false
# Configuration de la base de données pour Spring Batch (utilise la même DB que JPA)
spring.batch.jdbc.initialize-schema=always